name: API Integration 
on: 
  push:
    branches:
      - main
jobs:
  build_push_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout on master
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build api image
        run: docker image build -f api.Dockerfile . -t datatradingbot/trading_api:latest

      - name: Build tests image
        run: docker image build -f ./tests_integration/security/tests.Dockerfile ./tests_integration/security -t api_tests

      - name: Build predict tests image
        run: docker image build -f ./tests_integration/predict/tests.Dockerfile ./tests_integration/predict -t api_predict_tests

      - name: Tests
        run: cd ./tests_integration && ./start.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: datatradingbot
          password: dckr_pat_3NP8F1ds6ePlnSLHgE9C4fCfA1s

      - name: Push
        run: docker push datatradingbot/trading_api:latest