name: Control Push Unit tests
on: push
jobs:
  qa:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout on master
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.9"

      - name: Install pytest and necessary libraries
        run: |
          pip install pytest
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/domain/

      - name: Run flake8
        uses: py-actions/flake8@v2
        with:
          ignore: |
            "E501"
            "E251"
            "W292"
          path: "tests"
        
